### PR TITLE
Added the summoner name search function

### PR DESCRIPTION
**Pull request by LeonTeraoka**
Summary
Added a search function for summoner names.
We added OR summoner_name LIKE? to line 49 of teams.rb.

Result
You can search for a summoner name from the search form.

### CODE REVIEW

**Comment by LeonTeraoka** [comment]
resolve #134

**Comment by rutko** [comment]
Can i request one?
I want you to separate keyword search and summoner name search! 🙂

**Comment by LeonTeraoka** [comment]
@rutko 
OK. I'll come back to report you on the 21st Jan.

**Comment by LeonTeraoka** [comment]
@rutko 
I have forwarded your request to my assistant.

**Pull request closed without merging**
