### PR TITLE
Fixed the card position to left side

### LINKED ISSUE #121: Team cards is sort right
## Summary
Please fix the view of the team card.
Since it looks a little bit right side from the above.

## FYI
iOS の画像

### PR DESCRIPTION
**Pull request by LeonTeraoka**
Summary
Fixed padding 0 55px → padding 0 35px in teams.scss

Result
Adjust the position to a little bit left side of the card.

close #121

### CODE REVIEW

**Review by rutko — COMMENTED** [review]
Layout broken still.

**Comment by LeonTeraoka** [comment]
Now I think it looks well.
I just recover the padding and centered.

Regarding your comment, you can say like below.
Layout broken still. → The layout is still broken.

Looking forward to your review.

**Comment by rutko** [comment]
`padding: 0 55px;` も消しちゃってもいいかもしれない

**Comment by LeonTeraoka** [comment]
Thanks for the review.
We would like to look into your suggestion before the merge.
"padding: 0 55px; you could also able to delete this."
Kind Regards,

**Pull request merged**
