### PR TITLE
New posts have to come at the beginning

### LINKED ISSUE #74: 新しい投稿は上から表示されるようにしませんか？
新規投稿を見るたびにスクロールしなきゃいけないじゃん！

### PR DESCRIPTION
**Pull request by LeonTeraoka**
Fixes #74
Added your suggestion (order method)

### CODE REVIEW

**Review by rutko — CHANGES_REQUESTED** [review]
ありがとうございます！
これは今見つけてしまった不具合で申し訳ないのですが、get_teamというのはindexとsearchアクションの前に呼ばれるメソッドとなるはずなのですが、実際はsearchアクションで@teamsを再定義してしまっているので、そちらにもorderをつける必要があります。（そして、`before_action: get_teams, only: [:index, :search]`からsearchを外す必要がありますね🙏

そして可能であれば、oreder(update_at: :desc)で絞るほうがいいかもしれない

**Comment by LeonTeraoka** [comment]
First, I changed the "id" to "updated_at".
Because the goal is to show the latest update from the top. Not the order in id.
I also added the order method on the search to make as same as the above.
Now the search can also show the updates from the top.

Regarding the before_action, I understand there is a redefinition of the search.
But I didn't get the reason why do we have to delete the search on that.
Because my local test works correctly, and I can not figure out what is wrong.
But I think you are correct, so I fixed it.
It will be nice if you could clarify this for me.
I'm looking forward to your explanation.

Fixes #74

**Review by rutko — APPROVED** [review]
👏　plz merge this pull request 
LGTM

📝This is better way!

Currently there are two commits.
Can combine into one!
https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by LeonTeraoka** [comment]
Alright. Thanks for your review.
Let me combine them before I merge.

**Pull request merged**
